### ISSUE TITLE
Warning about missing Google SDK

### ISSUE THREAD

**Issue by michelletan** [molamolastudio/biolifetracker-iOS#18]
![screen shot 2015-04-04 at 12 42 52 pm](https://cloud.githubusercontent.com/assets/7555866/6991459/314e91a6-dac8-11e4-97e0-6744d2efac4a.png)

**Comment by nicholette** [comment]
Oh hmm.. it referenced to my path. Can it run currently? If not I will try to settle it before merging to master again.

**Comment by michelletan** [comment]
Is there a way to make it so that it references relative to the project's folder? O:

**Comment by nicholette** [comment]
i got rid of the problem. now just trying to settle the CRUD portion before merging into master again

**Comment by michelletan** [comment]
Okay, thanks :D
