### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by nicholette** [molamolastudio/biolifetracker-iOS#2]

**Comment by andhieka** [comment]
Precious Information for Sign Up / Sign In using Parse and Facebook account:
- https://www.parse.com/tutorials/integrating-facebook-in-ios (this will 'wrap' Facebook SDK)
- https://developers.facebook.com/docs/ios/getting-started (to know more about Facebook features. Maybe will not used directly if we use Parse PFFacebookUtil)
